### ISSUE TITLE
Billeder på mobile enheder

### ISSUE THREAD

**Issue by Loenberg** [AJenbo/agcms#14]
Hej Anders,
Fik lige støvet min gamle GitHub konto af  :-)
Dejligt med en udførlige oversigt over rettelserne som du sendte den anden dag.

Jeg har lige et spørgsmål omkring mobil kompatibilitet og billeder.

Jeg har lavet disse sider, hvor billederne ser mærkelige ud på mobilen.
https://huntershouse.dk/search/results/?q=spypoint

Hvad gør jeg forkert?

Ovenstående er blot et eksempel, der er også gamle sider hvor det ser underligt ud.
Har også sendt den på mail, blot for at Ole kan følge med :-)
Venlig hilsen Carsten

P.S. Fremtidige issues skal nok blive kortere......

**Comment by AJenbo** [comment]
Hej Carsten

Tak for fejl rapporten. Jeg har mest testet thema for AG og hade ikke lige fået lavet samme justering for de to andre sider. Det vil være rettet efter næste udgivelse, men det vil tage en måned der efter før alle brugere ser forbedringen pga. cache (cache busting er stadig ikke implementeret).

Mvh Anders
