### ISSUE TITLE
Kan ikke oprette ny kategori

### ISSUE THREAD

**Issue by Loenberg** [AJenbo/agcms#24]
Når jeg forsøger at oprette en ny kategori, får jeg denne fejlbesked: Gælder både firefox & Chrome
Error: Argument 2 passed to App\Services\OrmService::getOne() must be of the type integer, null given, called in /customers/7/8/5/huntershouse.dk/httpd.www/inc/Http/Controllers/Admin/CategoryController.php on line 69

**Comment by AJenbo** [comment]
https://sentry.io/anders-jenbo/agcms/issues/501726477/

**Comment by AJenbo** [comment]
Prøv at sikre dig at der er valgt en overliggende kategori, det ser ud som om det er problemet (men skal selfølig ikke kunne lade sig gøre i første omgang)

**Comment by Loenberg** [comment]
Som du kan se på dette screendump er Radiobutton markeret i ovenstående kategori. Jeg har prøvet på 2 maskiner.
![kategori fejl](https://user-images.githubusercontent.com/3041958/37963080-824f50be-31bd-11e8-90de-d5e61a2fd54f.jpg)

**Comment by Loenberg** [comment]
Har ud haft tid til at se på denne issue?

**Comment by AJenbo** [comment]
Skal nok holde jer informeret
