### ISSUE TITLE
Opdatering af Betingelser på Armsgallery.dk

### ISSUE THREAD

**Issue by Loenberg** [AJenbo/agcms#25]
28.06.18: Jeg har i dag opdateret menupunktet betingelser på Armsgallery.dk
Jeg gjorde følgende: 
1. flyttede den gamle side der hed "Betingelser" til inaktive under Handelsebetingelser.
2. Oprettede en ny side der hed Betingelser og lagde den under "Forside"
3. Første gang man klikker på "Betingelser" i topmenuen åbner den et søgeresultat og ikke direkte ind på siden. Anden gang man klikker åbner den betingelser. Hvad er gået galt?
Screen dump: 
![image](https://user-images.githubusercontent.com/3041958/42036626-58ab912e-7ae6-11e8-9c0c-3773967034c9.png)
URL: https://arms-gallery.dk/search/results/?q=Betingelser&sogikke=&minpris=&maxpris=&maerke=0

URL burde være: https://arms-gallery.dk/side5806-Betingelser.html

**Comment by AJenbo** [comment]
Jeg kan ikke genskabe problemet, det er nok igen caching der driller dig. Grunden til at det virker anden gang er at du er på søge siden som jo ikke har været indlæst tidligere og der for ikke er cachet i din browser.
Prøv at kopiere det link du klikker på når det ikke virker, så vil du nok kunne se at ID nok er forskelligt fra det der virker.

Closing; duplicate of #22
