### ISSUE TITLE
Dankort svindel - Ip adresse

### ISSUE THREAD

**Issue by Loenberg** [AJenbo/agcms#27]
På online HH20937 er der brugt et falsk Dankort / Stjålet Dankort.
Er det muligt at se hvilken Ip-adresse bookingen kommer fra?
Samt selve betalings ip-adressen, såfremt det ikke er den samme.
Detaljerede informationer kan hentes i E-pay

**Comment by AJenbo** [comment]
As far as I know this information is only available if you pay for there anti fraud package.

**Comment by AJenbo** [comment]
http://epay.bambora.com/da/betalingswebservice

**Comment by AJenbo** [comment]
http://epay.bambora.com/da/brug-af-fraud-fighter
